<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VDC1ODCD200101" failures="2" tests="2" name="Default test(failed)" time="0.156" errors="0" timestamp="2023-09-16T13:14:51 IST">
  <testcase classname="interview_Questions.failed_TestCases" name="testcase1" time="0.033">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at interview_Questions.failed_TestCases.testcase1(failed_TestCases.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <testcase classname="interview_Questions.failed_TestCases" name="testcase2" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at interview_Questions.failed_TestCases.testcase2(failed_TestCases.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- Default test(failed) -->
